import { getShapeRotations, rotationSymmetries, shapes } from './shapes';
import { findAllSolutions } from './solver';
import { mapObject } from './tools';

console.time('findAllSolutions');
// findAllSolutions();
console.timeEnd('findAllSolutions');

console.log(JSON.stringify(mapObject(shapes, getShapeRotations)));
// console.log(JSON.stringify(mapObject(shapes, rotationSymmetries)));

const a = {
    triangle: [
        [
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 1, direction: 'down' },
            { x: 0, y: 1, direction: 'up' },
            { x: 0, y: 2, direction: 'down' },
            { x: 0, y: 2, direction: 'up' },
            { x: 0, y: 3, direction: 'up' },
            { x: 1, y: 0, direction: 'down' },
            { x: 1, y: 0, direction: 'up' },
            { x: 1, y: 1, direction: 'down' },
            { x: 1, y: 1, direction: 'up' },
            { x: 1, y: 2, direction: 'up' },
            { x: 2, y: 0, direction: 'down' },
            { x: 2, y: 0, direction: 'up' },
            { x: 2, y: 1, direction: 'up' },
            { x: 3, y: 0, direction: 'up' },
        ],
        [
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 1, direction: 'down' },
            { x: 0, y: 1, direction: 'down' },
            { x: 0, y: 1, direction: 'up' },
            { x: 0, y: 2, direction: 'down' },
            { x: 0, y: 2, direction: 'down' },
            { x: 0, y: 2, direction: 'down' },
            { x: 0, y: 2, direction: 'up' },
            { x: 0, y: 2, direction: 'up' },
            { x: 0, y: 3, direction: 'down' },
            { x: 0, y: 3, direction: 'down' },
            { x: 0, y: 3, direction: 'down' },
            { x: 0, y: 3, direction: 'down' },
            { x: 0, y: 3, direction: 'up' },
            { x: 0, y: 3, direction: 'up' },
            { x: 0, y: 3, direction: 'up' },
        ],
        [
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
        ],
        [
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
        ],
        [
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
        ],
        [
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'down' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
            { x: 0, y: 0, direction: 'up' },
        ],
    ],
};
